### ISSUE TITLE
Later update flutter 1.2 today.

### ISSUE THREAD

**Issue by juanlabrador** [RomanBase/code_field#1]
../../flutter/.pub-cache/hosted/pub.dartlang.org/code_field-0.3.0/lib/src/input_code_field.dart:289:7: Error: The non-abstract class '_InputCodeFieldState' is missing implementations for these members:
 - TextInputClient.currentAutofillScope
 - TextInputClient.showAutocorrectionPromptRect
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

**Comment by RomanBase** [comment]
Hi, thanks for notice.
Version `0.3.1` now supports latest Flutter version and implements new `TextInputClient` API..
