### ISSUE TITLE
Error with latest Flutter update

### ISSUE THREAD

**Issue by ghost** [RomanBase/code_field#2]
Hi! I just updated Flutter and when I try to build I get this error:

Error: The non-abstract class '_InputCodeFieldState' is missing implementations for these members:
 - TextInputClient.performPrivateCommand
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _InputCodeFieldState extends State<InputCodeField> implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/services/text_input.dart:813:8: Context: 'TextInputClient.performPrivateCommand' is defined here.
  void performPrivateCommand(String action, Map<String, dynamic> data);
       ^^^^^^^^^^^^^^^^^^^^^

**Comment by RomanBase** [comment]
Hi, thanks for notice.
Version 1.22.0 now supports latest stable Flutter version (1.22.0) and implements new ``TextInputClient`` API.
